### ISSUE TITLE
bug in serial connection GUI code

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#12]
A recent API change, geared towards splitting completely the serial connection from the parsing of data also at module level, has left the GUI in a broken, inconsistent state.
When clicking on the //Connect// button, this error appears in the console:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.5/lib-tk/Tkinter.py", line 1417, in __call__
    return self.func(*args)
  File "./totalopenstation-gui.py", line 655, in connect_action
    mc = iformats.ModelConnector(chosen_port)
AttributeError: 'dict' object has no attribute 'ModelConnector'
```

Our plan for the serial connection is to get rid of "models" in the code, enable users to define their connection parameters in the GUI (saved in a preferences file), but then this change should be implemented for 0.2.

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/12
- Originally reported by: Stefano Costa
- Originally created at: 2010-01-16T15:58:05.743

**Comment by steko** [comment]
_From Stefano Costa on 2010-02-08 16:50:27+00:00_

Fixed in <<cset e13bcd56a59ec96602d1ae56413a2e14db8c7392>>
