### ISSUE TITLE
[BUG] app doesn't start on Windows 

### ISSUE THREAD

**Issue by psolyca** [totalopenstation/totalopenstation#124]
**Describe the bug**
When using the Windows app, Total Open Station do not open.
The message is :

```
D:\totalopenstation\dist>totalopenstation.exe
Traceback (most recent call last):
  File "totalopenstation\utils\upref.py", line 58, in __init__
  File "totalopenstation\utils\upref.py", line 92, in getvalue
  File "configparser.py", line 780, in get
  File "configparser.py", line 1146, in _unify_values
configparser.NoSectionError: No section: 'topsconfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "totalopenstation-gui.py", line 806, in <module>
  File "totalopenstation-gui.py", line 353, in __init__
  File "totalopenstation\utils\upref.py", line 60, in __init__
  File "totalopenstation\utils\upref.py", line 69, in initfile
AttributeError: 'NoneType' object has no attribute 'info'
[944] Failed to execute script totalopenstation-gui
```

**To Reproduce**
1. Launch a command prompt
2. Go to totalopenstation folder 
3. Start totalopenstation.exe

**Expected behavior**
Total Open Station start ^^

**Desktop (please complete the following information):**
 - Operating system: Windows 7
 - Software version 0.5

**Comment by SMSmith** [comment]
Confirmed this also affects:

- Operating System: Windows 10

**Comment by SMSmith** [comment]
Looks like if you can put whatever should be as default in ~/.totalopenstation/totalopenstation.cfg like the following, it runs.  
```
[topsconfig]
model = leica_tcr_1205
port = 4
sleeptime = 1.0
```

**Comment by steko** [comment]
Thank you @SMSmith it's exactly the missing file that causes the error. I wonder if this is limited to Windows.

**Comment by steko** [comment]
Waiting for review, this was caused by a concatenation of two separate bugs in the same file. By the way it's not limited to Windows, but it's difficult to test the GUI app in an isolated environment like the command line programs.
