### ISSUE TITLE
[BUG] "ModuleNotFoundError: No module named 'tkinter'" for

### ISSUE THREAD

**Issue by mavosaure** [totalopenstation/totalopenstation#139]
**Describe the bug**
After a pip3 install on Xubuntu 20.04:
```
~$ pip3 install --upgrade totalopenstation
Collecting totalopenstation
  Using cached totalopenstation-0.5.2-py3-none-any.whl (79 kB)
Requirement already satisfied, skipping upgrade: pyserial==3.4 in ./.local/lib/python3.8/site-packages (from totalopenstation) (3.4)
Requirement already satisfied, skipping upgrade: pygeoif==0.7 in ./.local/lib/python3.8/site-packages (from totalopenstation) (0.7)
Installing collected packages: totalopenstation
Successfully installed totalopenstation-0.5.2
```
As I launched the GUI, I got the following error:
```
~$ totalopenstation-gui.py
Traceback (most recent call last):
  File "/home/mav/.local/bin/totalopenstation-gui.py", line 29, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter
```
**To Reproduce**```
1. On Ubuntu 20.04 (pre-req install **python3-pip**), open a terminal
2. Do a fresh install of TOPS with 
  pip3 install --upgrade totalopenstation
3. Run the GUI with
  totalopenstation-gui.py
```
~$ totalopenstation-gui.py
Traceback (most recent call last):
  File "/home/mav/.local/bin/totalopenstation-gui.py", line 29, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter
```
**Expected behavior**
Probably a dependance problem with TkInter. 
Is it possible:
- to solve it in the pip package? 
- or to document it in the install process?

**Desktop (please complete the following information):**
 - Operating system: Xubuntu 20.04, x86_64
 - Software version: 0.5.2

**Comment by mavosaure** [comment]
As seen with @steko , the prerequisite on the Ubuntu family 20.04 is to install the *python3-tk* package, with something as 
     `sudo apt install python3-tk`
for example.

To document in the PIP install process ?
