### ISSUE TITLE
First run fails if .totalopenstation directory exists but .totalopenstation.cfg file doesn't

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#21]
Testing installation on Windows revealed a bug in upref.py that occurs in certain situations when totalopenstation-gui.py is run for the first time.

```
(pyenv)steko@ganymede:~/code/totalopenstation$ totalopenstation-gui.py 
Traceback (most recent call last):
  File "/home/steko/code/totalopenstation/pyenv/bin/totalopenstation-gui.py", line 7, in <module>
    execfile(__file__)
  File "/home/steko/code/totalopenstation/scripts/totalopenstation-gui.py", line 719, in <module>
    Tops = Tops(root)
  File "/home/steko/code/totalopenstation/scripts/totalopenstation-gui.py", line 319, in __init__
    self.upref = UserPrefs()
  File "/home/steko/code/totalopenstation/totalopenstation/utils/upref.py", line 54, in __init__
    os.mkdir(os.path.dirname(self.upref))
OSError: [Errno 17] File exists: '/home/steko/.totalopenstation'
```

This bug is caused by a missing condition handling in the function that creates the configuration file if missing.

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/21
- Originally reported by: Stefano Costa
- Originally created at: 2011-02-14T23:16:49.491

**Comment by steko** [comment]
_From Stefano Costa on 2011-02-15 15:30:35+00:00_

Fixed in <<cset ee2898f1f94f91fdcee52a3e243e9181ee6a8023>>.
