### ISSUE TITLE
Issues connecting to the serial port on Windows

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#23]
Issues connecting to COM ports under Windows have been reported by some users. This is Windows-specific and it's not directly related to TOPS nor Python, but nevertheless leaves users without a clue on how to download data from their total stations.

First of all, we should write a more detailed documentation to help these users.

Secondly, we should catch the specific exceptions that occur with this kind of problem, and give instructions on workarounds.

Finally, we should investigate if we are able to play with serial ports from within Python to prevent this problem at all.

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/23
- Originally reported by: Stefano Costa
- Originally created at: 2011-06-12T18:24:02.177

**Comment by steko** [comment]
_From Stefano Costa on 2011-06-12 16:25:00+00:00_

Documentation was updated in <<cset 03e26ac1e4d54693f22677a89ec820c5fb3d9a6a>>.

**Comment by steko** [comment]
_From Stefano Costa on 2011-06-14 21:28:45+00:00_

Here follows the complete report by Maxim Jaffe.

> I'm using TOPS on Windows XP, with Python 2.5.2 installed, to download data from a Leica TCR 407 but can seem to connect to the device. Since the model is not one of the options available used the custom option and specified everything based on what the devices manual says:
> 
> Baud rate: 19200
> Bytesize: 8
> Parity setting: N
> Stop bit: 1
> 
> Im using a usb to serial cable with all the necessary drivers installed and the COM port shows up in the device manager as COM4.
> 
> The output message from the gui is:
> 
> could not open port COM4: [Error 5] Acesso negado.
> 
> N.B. "Acesso negado" is portuguese for "Access denied"
> 
> The command prompt outputs the following:

```
#!pytb
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python25\lib\lib-tk\Tkinter.py", line 1403, in __call__
    return self.func(*args)
  File "C:\Python25\Scripts\totalopenstation-gui.py", line 662, in connect_action
    TOPSerial.open()
  File "C:\Python25\Lib\site-packages\serial\serialwin32.py", line 56, in open
    raise SerialException("could not open port %s: %s" % (self.portstr, ctypes.WinError()))
SerialException: could not open port COM4: [Error 5] Acesso negado.
```

> I've tried another proprietary software to connect to it and it seems find and even tried Hyperterminal and although I don't really know how to use it, seems like something happens since the device turns on and beeps when I tried to echo something.

**Comment by steko** [comment]
_From Stefano Costa on 2011-08-09 09:46:39+00:00_

Looks like the problem is with pySerial 2.5 ‒ earlier version 2.4 works fine for me on Windows XP (but it requires installing the pywin32 package beforehand).

Needs some documentation before it is properly fixed.

**Comment by steko** [comment]
_From Stefano Costa on 2011-11-09 21:17:13+00:00_

We are waiting for feedback on the step-by-step guide to installing TOPS on Microsoft Windows available on the project wiki at https://bitbucket.org/steko/totalopenstation/wiki/InstallingOnWindows ‒ this procedure has been tested by us already on Windows XP but before moving it to the official documentation we would like some more feedback from other users.

After that, this ticket will be marked as fixed.

**Comment by steko** [comment]
_From Stefano Costa on 2011-11-30 07:16:43+00:00_

Fixed in <<cset 5f197cebd7bfa174c30285b3e27398b1e28f13b8>>.

**Comment by steko** [comment]
_From Stefano Costa on 2013-06-13 19:09:11+00:00_

We had other reports of this issue affecting Windows users who are using pySerial 2.5 (perhaps because there is no binary installer for pySerial 2.6?).

**Comment by steko** [comment]
Marking as fixed since [pySerial](http://pyserial.sf.net/) 2.7 has been available for a while now, and our current documentation clearly explains not to use earlier versions (see 2e9ff3d08ad7d).
