### ISSUE TITLE
TOPS > 0.3 does not start if preferences from 0.3 exist

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#45]
TOPS 0.3 first introduced user preferences for the GUI, enabling the model and port choice to be saved across session.

Newer (unreleased) versions added more values to the saved choices (e.g. the `sleeptime` custom option), but if an old file exists without these choices the program will fail to start:

```
#!pytb

(pyenv)steko@ganymede:~/code/totalopenstation$ totalopenstation-gui.py 
Traceback (most recent call last):
  File "/home/steko/code/totalopenstation/pyenv/bin/totalopenstation-gui.py", line 7, in <module>
    execfile(__file__)
  File "/home/steko/code/totalopenstation/scripts/totalopenstation-gui.py", line 797, in <module>
    Tops = Tops(root)
  File "/home/steko/code/totalopenstation/scripts/totalopenstation-gui.py", line 605, in __init__
    self.option6_value.set(self.upref.getvalue('sleeptime'))
  File "/home/steko/code/totalopenstation/totalopenstation/utils/upref.py", line 86, in getvalue
    return self.get('topsconfig', value)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'sleeptime' in section: 'topsconfig'

```

An upgrade path must be provided, creating the missing variables when needed.

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/45
- Originally reported by: Stefano Costa
- Originally created at: 2013-06-14T12:19:30.514

**Comment by steko** [comment]
_From Stefano Costa on 2013-06-14 11:43:09+00:00_

Fixed in 995d85127dcb8410e83baa0d8f83e45603f5095b
