### ISSUE TITLE
Test suite doesn't check all possible combinations of input and output formats

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#85]
When trying to convert one of the sample data files to CSV from the GUI, this happens:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/tkinter/simpledialog.py", line 219, in ok
    self.apply()
  File "/home/steko/Scaricati/totalopenstation/scripts/totalopenstation-gui.py", line 309, in apply
    sd_file.write(output.process())
  File "/home/steko/Scaricati/totalopenstation/totalopenstation/output/tops_csv.py", line 53, in process
    feature.point_name,
  File "/home/steko/Scaricati/totalopenstation/totalopenstation/formats/__init__.py", line 52, in point_name
    return self.properties['point_name']
KeyError: 'point_name'
```

This is not caught by our current test suite since the input data used to test the output modules is a fake version. We should run tests in a way that allows testing all input formats against all output formats.

**Comment by steko** [comment]
> We should run tests in a way that allows testing all input formats against all output formats.

I have a working implementation of this comprehensive testing suite.

**Comment by psolyca** [comment]
I tried to implement all possibilities by using a coverage tool but didn't finished yet as it is as you see very huge.
Thus, I tried to remove all unnecessary code.
Will see later.

**Comment by steko** [comment]
As I wrote in my previous comment I already have a working implementation, based on pytest parametrization.

I'm waiting for your review of the main pull request #83 before pushing.

**Comment by steko** [comment]
When we add the new pytest based suite, `tests_require=['pytest']` must be added to `setup.py`.
