### ISSUE TITLE
Processing data from Sokkia SDR33 to GeoJSON fails with error

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#86]
This issue is only present in the GUI processing, the same conversion works well from the command line.

```
$ totalopenstation-gui.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/tkinter/simpledialog.py", line 219, in ok
    self.apply()
  File "/home/steko/Scaricati/totalopenstation/scripts/totalopenstation-gui.py", line 309, in apply
    sd_file.write(output.process())
TypeError: a bytes-like object is required, not 'str'
```

That's part of the switch to Python 3 outlined in issue #32.

**Comment by steko** [comment]
The command line tool works well because it opens the file object with `open(outfile, 'w')`, whereas the GUI calls `open(sd, 'wb')`.

I'm unsure what is the best action here, of course the difference between the two must be removed and possibly also not have duplication of code (even though that's one line..).

**Comment by steko** [comment]
In any case, changing the call to use `'w'` fixes the specific problem.

In general, it looks like it makes sense to use text mode since all our output formats are made of text files.
